name: Lints

on:
  push:
    branches: [ dieeasy/prot_act ]
  pull_request:
    branches: [ dieeasy/prot_act ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install rust 1.47.0
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.47.0
          override: true
          components: rustfmt
      - uses: actions-rs/cargo@v1
        name: Lints
        with:
          command: fmt
          args: --manifest-path rust-lib/Cargo.toml --all -- --check
